name = "hologramgong"
main = "src/index.ts"
compatibility_date = "2024-11-12"
compatibility_flags = ["nodejs_compat"]
account_id = "fbaa804209ab68a25daccf0076477227"

[[kv_namespaces]]
binding = "OAUTH_KV"
id = "a45d3cf019bf4dada9f782eec92b0bdc"

[observability]
enabled = true
